{% set name = "amep" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amep-{{ version }}.tar.gz
  sha256: 2eb87d4d724a78a9beb9f0be3eaa78af0e2fbc952dbe7676d4d11ed0a987baa4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=64
    - pip
  run:
    - python >=3.10
    - h5py >=3.7.0
    - matplotlib-base >=3.6.2
    - numba >=0.56.4
    - numpy >=1.26.6
    - scipy >=1.10.0
    - scikit-image >=0.20.0
    - tqdm >=4.65.0

test:
  imports:
    - amep
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Active Matter Evaluation Package for data analysis of active matter simulations
  home: https://amepproject.de/
  dev_url: https://github.com/amepproject/amep
  doc_url: https://amepproject.de/
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - LICENSES.third-party

extra:
  recipe-maintainers:
    - hechtprojects
